In [20]:
uv sync

Note: you may need to restart the kernel to use updated packages.

c:\Users\Ready2Use\Desktop\my-folder\Ironhack-week5\2nd-project\.venv\Scripts\python.exe: No module named uv

In [2]:
import pandas as pd
import seaborn as sns
import yaml
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

ModuleNotFoundError: No module named 'scipy'

In [3]:
with open("../config.yaml", "r") as file:
    config = yaml.safe_load(file)

In [4]:
clients_test = pd.read_csv(config["output_data"]["file4"])
clients_test

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,test
1,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0,test
2,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,test
3,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,test
4,8198645,15.0,189.0,54.5,F,2.0,382303.83,6.0,9.0,test
...,...,...,...,...,...,...,...,...,...,...
26956,501496,23.0,281.0,35.0,F,2.0,32529.34,0.0,3.0,test
26957,1780858,21.0,262.0,68.5,M,3.0,372100.59,6.0,9.0,test
26958,5826160,20.0,249.0,56.5,F,2.0,44837.16,2.0,5.0,test
26959,8739285,19.0,229.0,69.5,F,2.0,44994.24,1.0,4.0,test
26960,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,test

In [9]:
clients_test.columns

Index(['client_id', 'clnt_tenure_yr', 'clnt_tenure_mnth', 'clnt_age', 'gendr',
       'num_accts', 'bal', 'calls_6_mnth', 'logons_6_mnth', 'variation'],
      dtype='str')

In [5]:
# Filter test group by gender
female_clients_test = clients_test[clients_test['gendr'] == 'F']

# Quick check 

print(f"Test Female: {len(female_clients_test)}")

Test Female: 8716

In [6]:
male_clients_test = clients_test[clients_test['gendr'] == 'M']
male_clients_test
print(f"Test male: {len(male_clients_test)}")

Test male: 8977

In [7]:
unknown_clients_test = clients_test[clients_test['gendr'] == 'U']
unknown_clients_test
print(f"Test unknown: {len(unknown_clients_test)}")

Test unknown: 9266

Computing the difference between male and female clients does not make sence when the group of clients with unknown gender is the biggest group. We decided to discard the gender hypothesis and go with tenure years instead.

In [11]:
tenure_control = pd.read_csv(config["output_data"]["file3"])
tenure_control

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation
0,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,control
1,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,control
2,3727881,5.0,71.0,30.5,U,2.0,23915.60,0.0,3.0,control
3,272934,5.0,66.0,58.5,U,2.0,27021.42,2.0,5.0,control
4,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,control
...,...,...,...,...,...,...,...,...,...,...
23522,6662941,7.0,84.0,36.0,F,2.0,83101.84,4.0,7.0,control
23523,2787512,23.0,283.0,48.0,F,3.0,123618.60,1.0,4.0,control
23524,9932367,23.0,280.0,57.0,F,2.0,94466.55,6.0,9.0,control
23525,4079649,23.0,276.0,62.5,M,3.0,57575.28,4.0,7.0,control
23526,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,control

In [14]:
tenure_test = clients_test
tenure_test

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,test
1,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0,test
2,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,test
3,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,test
4,8198645,15.0,189.0,54.5,F,2.0,382303.83,6.0,9.0,test
...,...,...,...,...,...,...,...,...,...,...
26956,501496,23.0,281.0,35.0,F,2.0,32529.34,0.0,3.0,test
26957,1780858,21.0,262.0,68.5,M,3.0,372100.59,6.0,9.0,test
26958,5826160,20.0,249.0,56.5,F,2.0,44837.16,2.0,5.0,test
26959,8739285,19.0,229.0,69.5,F,2.0,44994.24,1.0,4.0,test
26960,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,test

In [15]:
tenure_test.columns

Index(['client_id', 'clnt_tenure_yr', 'clnt_tenure_mnth', 'clnt_age', 'gendr',
       'num_accts', 'bal', 'calls_6_mnth', 'logons_6_mnth', 'variation'],
      dtype='str')

In [16]:
clients_test['clnt_tenure_yr'].unique()

array([ 6.,  5., 16., 30., 15.,  4.,  3., 11.,  8., 12.,  7., 19., 18.,
       23., 21.,  9., 14., 27., 24., 28., 13., 20., 10., 29., 17., 22.,
       25., 26., 32., 33., 35.,  2., 38., 31., 34., 36., 51., 47., 37.,
       40., 55., 48., 43., 49., 39., 42., 50., 46., 44.])

In [17]:
clients_test['logons_6_mnth'].unique()

array([9., 6., 4., 8., 7., 5., 3.])

In [18]:
# Check tenure in both groups
print("TEST GROUP:")
print(tenure_test['clnt_tenure_yr'].describe())

print("\nCONTROL GROUP:")
print(tenure_control['clnt_tenure_yr'].describe())

TEST GROUP:
count    26961.000000
mean        11.982901
std          6.844947
min          2.000000
25%          6.000000
50%         11.000000
75%         15.000000
max         55.000000
Name: clnt_tenure_yr, dtype: float64

CONTROL GROUP:
count    23527.000000
mean        12.087686
std          6.877531
min          2.000000
25%          6.000000
50%         11.000000
75%         16.000000
max         55.000000
Name: clnt_tenure_yr, dtype: float64